#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

#GREEN='\033[0;32m'
#RED='\033[0;31m'
#BOLD_TEXT='\033[1m'

#npx --no -- commitlint --edit "$1"
npx --no-install commitlint --edit "$1"

#regex="^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\([a-z \-]+\))?!?: .+$"

# get the commit message
#commit_message=$(cat "$1")
#
#if [[ "$commit_message" =~ $regex ]]; then
#   echo "${GREEN} ${BOLD_TEXT} Сообщение commit-a message написано верно - в соответсвии с Conventional Commit standards..."
#   exit 0
#fi
#
#echo "${RED} ${BOLD_TEXT} Сообщение commit-a написано не верно - не по стандартам Conventional Commit standard"
#echo "${GREEN}  Пример valid commit-message: "
#echo "  git commit -m 'feat(login): add new button' или git commit -m 'fix: add new button'"
#echo "  Подробнее: https://www.conventionalcommits.org/en/v1.0.0/#summary ${RED}"
#exit 1