# release action with semantic release
name: Release

on:
  push:
    branches: [main, master]



jobs:
  release:
    name: Release
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18.17.x
        uses: actions/setup-node@v2
        with:
          node-version: '18.17'
      - name: Install dependencies
        run: npm ci
      - name: Semantic Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.TEST_TOKEN }}